<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="25" total="45" passed="20">
  <reporter-output>
    <line>
      <![CDATA[验证在数据库中,执行对应SQL语句,可以正常执行成功]]>
    </line>
    <line>
      <![CDATA[验证在引导页最后一页界面,点击开始体验按钮后,可以正常进入登录界面]]>
    </line>
    <line>
      <![CDATA[验证在登录界面,输入正确的账号和密码,已连接网络和开启GPS定位权限时,点击登录按钮后,可以正常登录并进入设置解锁密码界面]]>
    </line>
    <line>
      <![CDATA[验证在新建订单界面,选择输入对应产品信息,点击下一步按钮后,可以正常进入产品列表界面]]>
    </line>
    <line>
      <![CDATA[验证在产品列表界面,选择对应产品信息,点击下一步按钮后,可以正常进入商品信息界面]]>
    </line>
    <line>
      <![CDATA[验证在商品信息界面,选择输入对应商品信息,点击下一步按钮后,可以正常进入客户信息界面]]>
    </line>
    <line>
      <![CDATA[验证在客户信息界面,上传输入对应客户身份证正反面照片信息,点击生成订单按钮后,可以正常进入基本信息界面]]>
    </line>
    <line>
      <![CDATA[验证在基本信息界面,选择输入对应客户基本信息,点击下一步按钮后,可以正常进入单位信息界面]]>
    </line>
    <line>
      <![CDATA[验证在单位信息界面,选择输入对应客户单位信息,点击下一步按钮后,可以正常进入联系人填写界面]]>
    </line>
    <line>
      <![CDATA[验证在联系人填写界面,选择输入对应客户联系人信息,点击下一步按钮后,可以正常进入绑定银行卡界面]]>
    </line>
    <line>
      <![CDATA[验证在绑定银行卡界面,输入对应客户银行卡信息,点击下一步按钮后,可以正常进入其他信息界面]]>
    </line>
    <line>
      <![CDATA[验证在其他信息界面,输入对应客户其他信息,点击下一步按钮后,可以正常进入芝麻信用认证界面]]>
    </line>
    <line>
      <![CDATA[验证在芝麻信用认证界面,点击跳过认证按钮后,可以正常跳过认证并进入运营商授权认证界面]]>
    </line>
    <line>
      <![CDATA[验证在运营商授权认证界面,点击跳过认证按钮后,可以正常跳过认证并进入影像证明界面]]>
    </line>
    <line>
      <![CDATA[验证在影像证明界面,上传对应客户影像证明照片,点击确认提交按钮后,可以正常弹出请输入登录密码,以验证身份界面]]>
    </line>
    <line>
      <![CDATA[验证在请输入登录密码,以验证身份界面,输入对应用户登录密码,点击确认按钮后,可以正常提交合同并进入成功提交界面]]>
    </line>
    <line>
      <![CDATA[验证在成功提交界面,点击查看订单按钮后,可以正常进入订单列表-审核中列界面]]>
    </line>
    <line>
      <![CDATA[验证在审核通过列界面,选择对应合同点击补传资料按钮后,可以正常进入补传资料界面]]>
    </line>
    <line>
      <![CDATA[验证在补传资料界面,输入上传对应手机串号和IMEI码照片,点击确认提交按钮后,可以正常提交成功并返回审核通过列界面,且出现确认注册按钮]]>
    </line>
    <line>
      <![CDATA[验证在数据库中,执行对应SQL语句,可以正常执行成功]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="0" started-at="2017-09-30T10:29:33Z" finished-at="2017-09-30T10:29:33Z">
    <groups>
    </groups>
  </suite> <!-- Suite -->
  <suite name="P2P/XD/XT_CooperationModel" duration-ms="1343744" started-at="2017-09-30T10:07:09Z" finished-at="2017-09-30T10:29:32Z">
    <groups>
    </groups>
    <test name="P2P_DR模式下购买手机系列A产品的测试场景点" duration-ms="682517" started-at="2017-09-30T10:07:09Z" finished-at="2017-09-30T10:18:31Z">
      <class name="TestCases.P2P_DR_Mobile_SeriesA">
        <test-method status="PASS" signature="stup()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="stup" is-config="true" duration-ms="43559" started-at="2017-09-30T18:07:09Z" finished-at="2017-09-30T18:07:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stup -->
        <test-method status="PASS" signature="Precondition()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="Precondition" duration-ms="610" started-at="2017-09-30T18:07:52Z" finished-at="2017-09-30T18:07:53Z">
          <reporter-output>
            <line>
              <![CDATA[验证在数据库中,执行对应SQL语句,可以正常执行成功]]>
            </line>
          </reporter-output>
        </test-method> <!-- Precondition -->
        <test-method status="FAIL" signature="case1()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case1" duration-ms="3658" started-at="2017-09-30T18:07:53Z" finished-at="2017-09-30T18:07:56Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_DR_Mobile_SeriesA.case1(P2P_DR_Mobile_SeriesA.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: 安装启动失败(实际结果和预期结果不一致)  Actual 【开始体验】  but found 【开始体验1】
	at org.testng.Assert.fail(Assert.java:94)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.checkEquals(CheckAction_Handler.java:103)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:40)
	... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
        <test-method status="PASS" signature="case2()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case2" duration-ms="1744" started-at="2017-09-30T18:07:56Z" finished-at="2017-09-30T18:07:58Z">
          <reporter-output>
            <line>
              <![CDATA[验证在引导页最后一页界面,点击开始体验按钮后,可以正常进入登录界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case2 -->
        <test-method status="PASS" signature="case3()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case3" duration-ms="21744" started-at="2017-09-30T18:07:58Z" finished-at="2017-09-30T18:08:20Z">
          <reporter-output>
            <line>
              <![CDATA[验证在登录界面,输入正确的账号和密码,已连接网络和开启GPS定位权限时,点击登录按钮后,可以正常登录并进入设置解锁密码界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case3 -->
        <test-method status="PASS" signature="case4()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case4" duration-ms="38177" started-at="2017-09-30T18:08:20Z" finished-at="2017-09-30T18:08:58Z">
          <reporter-output>
            <line>
              <![CDATA[验证在新建订单界面,选择输入对应产品信息,点击下一步按钮后,可以正常进入产品列表界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case4 -->
        <test-method status="PASS" signature="case5()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case5" duration-ms="4528" started-at="2017-09-30T18:08:58Z" finished-at="2017-09-30T18:09:03Z">
          <reporter-output>
            <line>
              <![CDATA[验证在产品列表界面,选择对应产品信息,点击下一步按钮后,可以正常进入商品信息界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case5 -->
        <test-method status="PASS" signature="case6()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case6" duration-ms="22210" started-at="2017-09-30T18:09:03Z" finished-at="2017-09-30T18:09:25Z">
          <reporter-output>
            <line>
              <![CDATA[验证在商品信息界面,选择输入对应商品信息,点击下一步按钮后,可以正常进入客户信息界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case6 -->
        <test-method status="PASS" signature="case7()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case7" duration-ms="77084" started-at="2017-09-30T18:09:25Z" finished-at="2017-09-30T18:10:42Z">
          <reporter-output>
            <line>
              <![CDATA[验证在客户信息界面,上传输入对应客户身份证正反面照片信息,点击生成订单按钮后,可以正常进入基本信息界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case7 -->
        <test-method status="PASS" signature="case8()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case8" duration-ms="199631" started-at="2017-09-30T18:10:42Z" finished-at="2017-09-30T18:14:02Z">
          <reporter-output>
            <line>
              <![CDATA[验证在基本信息界面,选择输入对应客户基本信息,点击下一步按钮后,可以正常进入单位信息界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case8 -->
        <test-method status="PASS" signature="case9()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case9" duration-ms="111841" started-at="2017-09-30T18:14:02Z" finished-at="2017-09-30T18:15:53Z">
          <reporter-output>
            <line>
              <![CDATA[验证在单位信息界面,选择输入对应客户单位信息,点击下一步按钮后,可以正常进入联系人填写界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case9 -->
        <test-method status="PASS" signature="case_10()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_10" duration-ms="41502" started-at="2017-09-30T18:15:53Z" finished-at="2017-09-30T18:16:35Z">
          <reporter-output>
            <line>
              <![CDATA[验证在联系人填写界面,选择输入对应客户联系人信息,点击下一步按钮后,可以正常进入绑定银行卡界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_10 -->
        <test-method status="PASS" signature="case_11()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_11" duration-ms="20384" started-at="2017-09-30T18:16:35Z" finished-at="2017-09-30T18:16:55Z">
          <reporter-output>
            <line>
              <![CDATA[验证在绑定银行卡界面,输入对应客户银行卡信息,点击下一步按钮后,可以正常进入其他信息界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_11 -->
        <test-method status="PASS" signature="case_12()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_12" duration-ms="12397" started-at="2017-09-30T18:16:55Z" finished-at="2017-09-30T18:17:08Z">
          <reporter-output>
            <line>
              <![CDATA[验证在其他信息界面,输入对应客户其他信息,点击下一步按钮后,可以正常进入芝麻信用认证界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_12 -->
        <test-method status="PASS" signature="case_13()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_13" duration-ms="2001" started-at="2017-09-30T18:17:08Z" finished-at="2017-09-30T18:17:10Z">
          <reporter-output>
            <line>
              <![CDATA[验证在芝麻信用认证界面,点击跳过认证按钮后,可以正常跳过认证并进入运营商授权认证界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_13 -->
        <test-method status="PASS" signature="case_14()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_14" duration-ms="2112" started-at="2017-09-30T18:17:10Z" finished-at="2017-09-30T18:17:12Z">
          <reporter-output>
            <line>
              <![CDATA[验证在运营商授权认证界面,点击跳过认证按钮后,可以正常跳过认证并进入影像证明界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_14 -->
        <test-method status="PASS" signature="case_15()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_15" duration-ms="32330" started-at="2017-09-30T18:17:12Z" finished-at="2017-09-30T18:17:44Z">
          <reporter-output>
            <line>
              <![CDATA[验证在影像证明界面,上传对应客户影像证明照片,点击确认提交按钮后,可以正常弹出请输入登录密码,以验证身份界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_15 -->
        <test-method status="PASS" signature="case_16()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_16" duration-ms="10616" started-at="2017-09-30T18:17:44Z" finished-at="2017-09-30T18:17:55Z">
          <reporter-output>
            <line>
              <![CDATA[验证在请输入登录密码,以验证身份界面,输入对应用户登录密码,点击确认按钮后,可以正常提交合同并进入成功提交界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_16 -->
        <test-method status="PASS" signature="case_17()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_17" duration-ms="2502" started-at="2017-09-30T18:17:55Z" finished-at="2017-09-30T18:17:57Z">
          <reporter-output>
            <line>
              <![CDATA[验证在成功提交界面,点击查看订单按钮后,可以正常进入订单列表-审核中列界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_17 -->
        <test-method status="FAIL" signature="case_18()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_18" duration-ms="6823" started-at="2017-09-30T18:17:57Z" finished-at="2017-09-30T18:18:04Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_DR_Mobile_SeriesA.case_18(P2P_DR_Mobile_SeriesA.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: 未发现审核通过的合同或合同状态未改变(实际结果和预期结果不一致)  Actual 【时雪多】  but found 【时雪】
	at org.testng.Assert.fail(Assert.java:94)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.checkEquals(CheckAction_Handler.java:103)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:40)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_18 -->
        <test-method status="PASS" signature="case_19()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_19" duration-ms="2150" started-at="2017-09-30T18:18:04Z" finished-at="2017-09-30T18:18:06Z">
          <reporter-output>
            <line>
              <![CDATA[验证在审核通过列界面,选择对应合同点击补传资料按钮后,可以正常进入补传资料界面]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_19 -->
        <test-method status="PASS" signature="case_20()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="case_20" duration-ms="22797" started-at="2017-09-30T18:18:06Z" finished-at="2017-09-30T18:18:29Z">
          <reporter-output>
            <line>
              <![CDATA[验证在补传资料界面,输入上传对应手机串号和IMEI码照片,点击确认提交按钮后,可以正常提交成功并返回审核通过列界面,且出现确认注册按钮]]>
            </line>
          </reporter-output>
        </test-method> <!-- case_20 -->
        <test-method status="PASS" signature="And()[pri:0, instance:TestCases.P2P_DR_Mobile_SeriesA@1d251891]" name="And" is-config="true" duration-ms="2110" started-at="2017-09-30T18:18:29Z" finished-at="2017-09-30T18:18:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- And -->
      </class> <!-- TestCases.P2P_DR_Mobile_SeriesA -->
    </test> <!-- P2P_DR模式下购买手机系列A产品的测试场景点 -->
    <test name="P2P_PPM模式下购买手机系列A产品的测试场景点" duration-ms="661115" started-at="2017-09-30T10:18:31Z" finished-at="2017-09-30T10:29:32Z">
      <class name="TestCases.P2P_PPM_Mobile_SeriesA">
        <test-method status="PASS" signature="stup()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="stup" is-config="true" duration-ms="29811" started-at="2017-09-30T18:18:31Z" finished-at="2017-09-30T18:19:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stup -->
        <test-method status="PASS" signature="Precondition()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="Precondition" duration-ms="527" started-at="2017-09-30T18:19:01Z" finished-at="2017-09-30T18:19:02Z">
          <reporter-output>
            <line>
              <![CDATA[验证在数据库中,执行对应SQL语句,可以正常执行成功]]>
            </line>
          </reporter-output>
        </test-method> <!-- Precondition -->
        <test-method status="FAIL" signature="case1()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case1" duration-ms="10063" started-at="2017-09-30T18:19:02Z" finished-at="2017-09-30T18:19:12Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case1(P2P_PPM_Mobile_SeriesA.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case1 -->
        <test-method status="FAIL" signature="case2()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case2" duration-ms="30583" started-at="2017-09-30T18:19:12Z" finished-at="2017-09-30T18:19:42Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case2(P2P_PPM_Mobile_SeriesA.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case2 -->
        <test-method status="FAIL" signature="case3()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case3" duration-ms="30243" started-at="2017-09-30T18:19:42Z" finished-at="2017-09-30T18:20:12Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case3(P2P_PPM_Mobile_SeriesA.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case3 -->
        <test-method status="FAIL" signature="case4()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case4" duration-ms="30398" started-at="2017-09-30T18:20:12Z" finished-at="2017-09-30T18:20:43Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case4(P2P_PPM_Mobile_SeriesA.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case4 -->
        <test-method status="FAIL" signature="case5()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case5" duration-ms="30581" started-at="2017-09-30T18:20:43Z" finished-at="2017-09-30T18:21:13Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case5(P2P_PPM_Mobile_SeriesA.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case5 -->
        <test-method status="FAIL" signature="case6()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case6" duration-ms="30434" started-at="2017-09-30T18:21:13Z" finished-at="2017-09-30T18:21:44Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case6(P2P_PPM_Mobile_SeriesA.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case6 -->
        <test-method status="FAIL" signature="case7()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case7" duration-ms="10544" started-at="2017-09-30T18:21:44Z" finished-at="2017-09-30T18:21:54Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case7(P2P_PPM_Mobile_SeriesA.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case7 -->
        <test-method status="FAIL" signature="case8()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case8" duration-ms="30551" started-at="2017-09-30T18:21:54Z" finished-at="2017-09-30T18:22:25Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case8(P2P_PPM_Mobile_SeriesA.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case8 -->
        <test-method status="FAIL" signature="case9()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case9" duration-ms="30052" started-at="2017-09-30T18:22:25Z" finished-at="2017-09-30T18:22:55Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case9(P2P_PPM_Mobile_SeriesA.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case9 -->
        <test-method status="FAIL" signature="case_10()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_10" duration-ms="30346" started-at="2017-09-30T18:22:55Z" finished-at="2017-09-30T18:23:25Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_10(P2P_PPM_Mobile_SeriesA.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_10 -->
        <test-method status="FAIL" signature="case_11()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_11" duration-ms="30411" started-at="2017-09-30T18:23:25Z" finished-at="2017-09-30T18:23:56Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_11(P2P_PPM_Mobile_SeriesA.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_11 -->
        <test-method status="FAIL" signature="case_12()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_12" duration-ms="30279" started-at="2017-09-30T18:23:56Z" finished-at="2017-09-30T18:24:26Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_12(P2P_PPM_Mobile_SeriesA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_12 -->
        <test-method status="FAIL" signature="case_13()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_13" duration-ms="10539" started-at="2017-09-30T18:24:26Z" finished-at="2017-09-30T18:24:37Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_13(P2P_PPM_Mobile_SeriesA.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_13 -->
        <test-method status="FAIL" signature="case_14()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_14" duration-ms="30325" started-at="2017-09-30T18:24:37Z" finished-at="2017-09-30T18:25:07Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_14(P2P_PPM_Mobile_SeriesA.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_14 -->
        <test-method status="FAIL" signature="case_15()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_15" duration-ms="10129" started-at="2017-09-30T18:25:07Z" finished-at="2017-09-30T18:25:17Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$2.run(Step_Action.java:41)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_15(P2P_PPM_Mobile_SeriesA.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_15 -->
        <test-method status="FAIL" signature="case_16()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_16" duration-ms="30360" started-at="2017-09-30T18:25:17Z" finished-at="2017-09-30T18:25:47Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_16(P2P_PPM_Mobile_SeriesA.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_16 -->
        <test-method status="FAIL" signature="case_17()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_17" duration-ms="10289" started-at="2017-09-30T18:25:47Z" finished-at="2017-09-30T18:25:58Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_17(P2P_PPM_Mobile_SeriesA.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_17 -->
        <test-method status="FAIL" signature="case_18()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_18" duration-ms="30078" started-at="2017-09-30T18:25:58Z" finished-at="2017-09-30T18:26:28Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_18(P2P_PPM_Mobile_SeriesA.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_18 -->
        <test-method status="FAIL" signature="case_19()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_19" duration-ms="30048" started-at="2017-09-30T18:26:28Z" finished-at="2017-09-30T18:26:58Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_19(P2P_PPM_Mobile_SeriesA.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_19 -->
        <test-method status="FAIL" signature="case_20()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_20" duration-ms="91221" started-at="2017-09-30T18:26:58Z" finished-at="2017-09-30T18:28:29Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_20(P2P_PPM_Mobile_SeriesA.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_20 -->
        <test-method status="FAIL" signature="case_21()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_21" duration-ms="31977" started-at="2017-09-30T18:28:29Z" finished-at="2017-09-30T18:29:01Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_21(P2P_PPM_Mobile_SeriesA.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_21 -->
        <test-method status="FAIL" signature="case_22()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_22" duration-ms="29199" started-at="2017-09-30T18:29:01Z" finished-at="2017-09-30T18:29:30Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_22(P2P_PPM_Mobile_SeriesA.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'King', ip: '192.168.98.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
Capabilities [{appPackage=com.giveu.corder, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=b62f7ec6, fullReset=false, platform=LINUX, appActivity=.index.activity.SplashActivity, desired={appPackage=com.giveu.corder, noReset=true, deviceName=Android Emulator, fullReset=false, appActivity=.index.activity.SplashActivity, newCommandTimeout=60000, platformVersion=4.2.2, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}, newCommandTimeout=60000, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}]
Session ID: 4afa3647-b9d3-4434-a52e-265fd71e5b6b
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:388)
	at io.appium.java_client.android.AndroidDriver.findElementsByAndroidUIAutomator(AndroidDriver.java:403)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
Caused by: org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'King', ip: '192.168.98.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 24 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy5.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:67)
	... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_22 -->
        <test-method status="FAIL" signature="case_23()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="case_23" duration-ms="1021" started-at="2017-09-30T18:29:30Z" finished-at="2017-09-30T18:29:31Z">
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_23(P2P_PPM_Mobile_SeriesA.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'King', ip: '192.168.98.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
Capabilities [{appPackage=com.giveu.corder, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=b62f7ec6, fullReset=false, platform=LINUX, appActivity=.index.activity.SplashActivity, desired={appPackage=com.giveu.corder, noReset=true, deviceName=Android Emulator, fullReset=false, appActivity=.index.activity.SplashActivity, newCommandTimeout=60000, platformVersion=4.2.2, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}, newCommandTimeout=60000, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}]
Session ID: 4afa3647-b9d3-4434-a52e-265fd71e5b6b
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:865)
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbQuery(DBAction_Handler.java:54)
	... 18 more
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'King', ip: '192.168.98.2', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 23 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:67)
	... 24 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 37 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case_23 -->
        <test-method status="PASS" signature="And()[pri:0, instance:TestCases.P2P_PPM_Mobile_SeriesA@57829d67]" name="And" is-config="true" duration-ms="1097" started-at="2017-09-30T18:29:31Z" finished-at="2017-09-30T18:29:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- And -->
      </class> <!-- TestCases.P2P_PPM_Mobile_SeriesA -->
    </test> <!-- P2P_PPM模式下购买手机系列A产品的测试场景点 -->
  </suite> <!-- P2P/XD/XT_CooperationModel -->
</testng-results>
